### ISSUE TITLE
Upload a new release of uuagc-cabal

### ISSUE THREAD

**Issue by FPtje** [UU-ComputerScience/uuagc#14]
Today I was playing with updating glualint to the latest GHC again, and found that https://github.com/UU-ComputerScience/uuagc/pull/12 did make it in a release of `uuagc` on hackage, but not `uuagc-cabal`.

This can be seen here:

https://hackage.haskell.org/package/uuagc-cabal-1.3.0.0/src/src/Distribution/Simple/UUAGC/Parser.hs

Version 1.3.0.0 still has the `instance Error ParserError`

Could you upload a new version of uuagc-cabal? Thanks!

**Comment by jbransen** [comment]
[Fixed](https://hackage.haskell.org/package/uuagc-cabal-1.3.1.0), thank you!
